# Generated by Django 3.2.7 on 2021-09-27 19:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0005_vehiclepassport'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
                ('objects_volvo', django.db.models.manager.Manager()),
            ],
        ),
    ]
