# Generated by Django 3.2.7 on 2021-09-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0006_alter_auto_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
            ],
        ),
    ]
