# Generated by Django 3.2.7 on 2021-10-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0010_auto_20211012_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='event',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='features',
        ),
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Enroll',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
